local_costmap:
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 5.0 #20
    publish_frequency: 5.0 #10
  
    rolling_window: true
    width: 2.0 #6.0
    height: 2.0 #6.0
    resolution: 0.05

  
    plugins: 
        - {name: static_layer,            type: "costmap_2d::StaticLayer"}
        - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
        - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}

    static_layer:
        enabled:              false # keep false so temporary objects do not clutter the map
        map_topic:            "/map"


    inflation_layer:
        enabled:              true
        cost_scaling_factor:  5
        inflation_radius:     0.35

    obstacle_layer:
        observation_sources: laser_scan_sensor
        footprint_clearing_enabled: true
        laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, clearing: true, marking: true}

